name: evergreen_lifechurch_todo
description: Evergreen todo app for life.church interview process
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: 3.24.3 # Make sure matches pipeline / build servers
  # TODO: Eventually use puro or fvm or flutterw or scripted versions.

dependencies:

  cloud_firestore: ^5.4.4
  fake_cloud_firestore: ^3.0.3
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_messaging: ^15.1.3
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true