name: evergreen_lifechurch_todo

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.24.3 #should match pubspec.yaml and flutter --version on dev
      # and qa machine. Eventually use puro/fvm/flutterw
      min_coverage: 60
      format_directories: lib
      analyze_directories: lib
      coverage_excludes: "**/*.g.dart **/*.freezed.g.dart"
